#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "Orca remote harness on a Proxmox VM"

# Remote helpers. BatchMode fails fast instead of prompting mid-wizard.
vm_ssh()     { ssh -o BatchMode=yes -o ConnectTimeout=10 "$ORCA_VM_USER@$ORCA_VM_HOST" "$@"; }
vm_ssh_tty() { ssh -t -o ConnectTimeout=10 "$ORCA_VM_USER@$ORCA_VM_HOST" "$@"; }
die() { printf '\n%s  ✗ %s%s\n' "$RED" "$1" "$RESET"; exit 1; }

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Proxmox — create the VM"
say "Create a Linux VM on the miniPC's Proxmox host. Ubuntu Server LTS is the tested target."
ask PROXMOX_URL "Proxmox web UI URL (e.g. https://192.168.68.100:8006):"
[[ -n "$PROXMOX_URL" ]] && open_url "$PROXMOX_URL"
step "Create a VM (2+ vCPU, 8 GB RAM, 64 GB disk) and install Ubuntu Server LTS."
step "Give it a fixed LAN address or a DHCP reservation, and install the OpenSSH server."
step "Set an SSH password or add your public key."
ask ORCA_VM_HOST "VM IP address:"
ask ORCA_VM_USER "VM SSH user [ubuntu]:"
ORCA_VM_USER="${ORCA_VM_USER:-ubuntu}"
write_env ORCA_VM_HOST "$ORCA_VM_HOST"
write_env ORCA_VM_USER "$ORCA_VM_USER"
write_env ORCA_RUNTIME_PORT "6768"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Reach the VM over SSH"
say "Checking ssh $ORCA_VM_USER@$ORCA_VM_HOST ..."
until vm_ssh true 2>/dev/null; do
  warn "SSH failed. Confirm the IP, that sshd is running, and that your key is installed."
  step "Copy your key if needed:  ssh-copy-id $ORCA_VM_USER@$ORCA_VM_HOST"
  pause "Press Enter to retry."
done
note "SSH works."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Base packages and Tailscale"
say "Installing git, curl, and jq on the VM."
vm_ssh 'sudo apt-get update && sudo apt-get install -y git curl jq' || die "package install failed"
say "Installing Tailscale."
vm_ssh 'curl -fsSL https://tailscale.com/install.sh | sh' || die "Tailscale install failed"
say "Joining the tailnet. This prints a login URL; approve it in your browser."
vm_ssh_tty 'sudo tailscale up'
ask ORCA_VM_MAGICDNS "VM Tailscale/MagicDNS name (e.g. orca.tailnet.ts.net):"
write_env ORCA_VM_MAGICDNS "$ORCA_VM_MAGICDNS"
note "Next time reach the VM at $ORCA_VM_USER@$ORCA_VM_MAGICDNS"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Install Orca and the agent toolchain"
say "Install these on the VM, then we verify each. Accounts and binaries live on the VM, not this Mac."
step "Orca's Linux build, from your Orca distribution link."
step "OpenCode (https://opencode.ai/docs) and your agent CLI (codex/claude)."
open_url "https://opencode.ai/docs"
pause "Press Enter once the installs are done."
for bin in orca opencode; do
  if vm_ssh "command -v $bin >/dev/null 2>&1"; then
    note "$bin installed"
  else
    warn "$bin is not on the VM's PATH yet"
    SKIPPED+=("$bin on the VM")
  fi
done

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Interactive logins on the VM"
say "Credentials are per host. Run these against the VM; use device-auth for agents,"
say "because a headless VM cannot receive an OAuth loopback callback."
step "ssh -t $ORCA_VM_USER@$ORCA_VM_MAGICDNS 'gh auth login'"
step "ssh -t $ORCA_VM_USER@$ORCA_VM_MAGICDNS 'codex login --device-auth'"
pause "Press Enter once the logins are done."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Run the Orca runtime as a service"
say "Installing a systemd unit so the runtime survives reboots."
orca_bin="$(vm_ssh 'command -v orca' || true)"
[[ -n "$orca_bin" ]] || die "orca is not on the VM's PATH; finish stage 4 first"
vm_ssh 'sudo tee /etc/systemd/system/orca.service >/dev/null' <<UNIT
[Unit]
Description=Orca runtime server
After=network-online.target tailscaled.service
Wants=network-online.target

[Service]
Type=simple
User=$ORCA_VM_USER
ExecStart=$orca_bin serve --port ${ORCA_RUNTIME_PORT} --pairing-address ws://${ORCA_VM_MAGICDNS}:${ORCA_RUNTIME_PORT} --mobile-pairing
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT
vm_ssh 'sudo systemctl daemon-reload && sudo systemctl enable --now orca' || die "could not start orca.service"
sleep 3
say "Pairing material from the runtime log:"
vm_ssh 'sudo journalctl -u orca -n 80 --no-pager'

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Pair the macOS and mobile apps"
say "Both apps pair to the one runtime and then share its worktrees and terminals."
step "Mobile: scan the QR printed by the runtime (it is in the log above)."
ask_secret ORCA_PAIRING_CODE "Paste the pairing link (orca://pair?code=...) for the macOS app:"
if [[ -n "$ORCA_PAIRING_CODE" ]] && command -v orca >/dev/null 2>&1; then
  if orca environment add --name miniPC --pairing-code "$ORCA_PAIRING_CODE" --json >/dev/null; then
    note "macOS app paired to the miniPC runtime"
  else
    warn "pairing failed; check that the Orca app is running"
  fi
else
  warn "orca is not on this Mac's PATH, or no code was entered"
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Register repositories on the VM"
say "Clone each project on the VM, then register it with the runtime."
step "ssh -t $ORCA_VM_USER@$ORCA_VM_MAGICDNS 'git clone <repo> ~/projects/<name>'"
step "orca repo add --path ~/projects/<name> --json"
step "orca repo set-base-ref --repo id:<id> --ref origin/main"
note "agentctl start-task registers a checkout automatically if it is missing."

finish
